name: Firestore Android snippets build

on:
  pull_request:
    paths:
    - 'firestore/android**'
    - '.github/workflows/firestore-android.yml'

jobs:
  firestore-android-build:
    name: Build snippets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download C++ SDK
        run: curl -o firestore/android/binary/firebase-cpp-sdk.zip https://dl.google.com/firebase/sdk/cpp/firebase_cpp_sdk_6.15.1.zip --create-dirs
      - name: Extract SDK
        run: unzip firestore/android/binary/firebase-cpp-sdk.zip -d firestore/android/binary
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Build with Gradle
        run: |
          cd firestore/android/FirestoreSnippetsCpp
          ./gradlew clean build

